backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "page"
    label: "Landing Page"
    files:
      - file: "index.html"
        label: "Homepage"
        fields:
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
            required: false
